# Generated by Django 4.1.7 on 2023-04-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
