# Generated by Django 4.1.7 on 2023-06-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_orderitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookproduct',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
    ]
