# Generated by Django 4.1.7 on 2023-06-16 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_bookproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookproduct',
            name='published',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
