# Generated by Django 4.1.7 on 2023-06-21 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_alter_bookproduct_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookproduct',
            name='published',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
