# Generated by Django 4.1.7 on 2023-06-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_alter_bookproduct_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookproduct',
            name='published',
            field=models.DateField(blank=True, null=True),
        ),
    ]
