# Generated by Django 4.1.7 on 2023-06-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_alter_bookproduct_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookproduct',
            name='category',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
