//SHOP HOMEPAGE
export const BOOKPRODUCT_LIST_REQUEST = 'BOOKPRODUCT_LIST_REQUEST'
export const BOOKPRODUCT_LIST_SUCCESS = 'BOOKPRODUCT_LIST_SUCCESS'
export const BOOKPRODUCT_LIST_FAIL = 'BOOKPRODUCT_LIST_FAIL'

//SHOP PRODUCT PAGE
export const BOOKPRODUCT_DETAILS_REQUEST = 'BOOKPRODUCT_DETAILS_REQUEST'
export const BOOKPRODUCT_DETAILS_SUCCESS = 'BOOKPRODUCT_DETAILS_SUCCESS'
export const BOOKPRODUCT_DETAILS_FAIL = 'BOOKPRODUCT_DETAILS_FAIL'

export const BOOKPRODUCT_DELETE_REQUEST = 'BOOKPRODUCT_DELETE_REQUEST'
export const BOOKPRODUCT_DELETE_SUCCESS = 'BOOKPRODUCT_DELETE_SUCCESS'
export const BOOKPRODUCT_DELETE_FAIL = 'BOOKPRODUCT_DELETE_FAIL'

export const BOOKPRODUCT_CREATE_REQUEST = 'BOOKPRODUCT_CREATE_REQUEST'
export const BOOKPRODUCT_CREATE_SUCCESS = 'BOOKPRODUCT_CREATE_SUCCESS'
export const BOOKPRODUCT_CREATE_FAIL = 'BOOKPRODUCT_CREATE_FAIL'
export const BOOKPRODUCT_CREATE_RESET = 'BOOKPRODUCT_CREATE_RESET'


export const BOOKPRODUCT_UPDATE_REQUEST = 'BOOKPRODUCT_UPDATE_REQUEST'
export const BOOKPRODUCT_UPDATE_SUCCESS = 'BOOKPRODUCT_UPDATE_SUCCESS'
export const BOOKPRODUCT_UPDATE_FAIL = 'BOOKPRODUCT_UPDATE_FAIL'
export const BOOKPRODUCT_UPDATE_RESET = 'BOOKPRODUCT_UPDATE_RESET'


export const BOOKPRODUCT_CREATE_REVIEW_REQUEST = 'BOOKPRODUCT_CREATE_REVIEW_REQUEST'
export const BOOKPRODUCT_CREATE_REVIEW_SUCCESS = 'BOOKPRODUCT_CREATE_REVIEW_SUCCESS'
export const BOOKPRODUCT_CREATE_REVIEW_FAIL = 'BOOKPRODUCT_CREATE_REVIEW_FAIL'
export const BOOKPRODUCT_CREATE_REVIEW_RESET = 'BOOKPRODUCT_CREATE_REVIEW_RESET'

export const BOOKPRODUCT_TOP_REQUEST = 'BOOKPRODUCT_TOP_REQUEST'
export const BOOKPRODUCT_TOP_SUCCESS = 'BOOKPRODUCT_TOP_SUCCESS'
export const BOOKPRODUCT_TOP_FAIL = 'BOOKPRODUCT_TOP_FAIL'