const books = [
  {
    _id: "1",
    title: "Eloquent JavaScript, Third Edition",
    subtitle: "A Modern Introduction to Programming",
    author: "Marijn Haverbeke",
    published: "2018-12-04",
    publisher: "No Starch Press",
    pages: 472,
    category: "Programming Books",
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
    image: "/images/book1.png",
  },
  {
    _id: "2",
    title: "Practical Modern JavaScript",
    subtitle: "Dive into ES6 and the Future of JavaScript",
    author: "Nicolás Bevacqua",
    published: "2017-07-16",
    publisher: "O'Reilly Media",
    pages: 334,
    category: "Programming Books",
    price: 180.99,
    countInStock: 0,
    rating: 4.0,
    numReviews: 8,
    image: "/images/book2.png",
  },
  {
    _id: "3",
    title: "Atomic Habits",
    subtitle: "An Easy & Proven Way to Build Good Habits & Break Bad Ones Hardcover",
    author: "James Clear",
    published: "2018-10-16",
    publisher: "Avery",
    pages: 320,
    category: "Self-Help Books",
    price: 60.99,
    countInStock: 15,
    rating: 5.0,
    numReviews: 20,
    image: "/images/book3.png",
  },
  {
    _id: "4",
    title: "Sapiens",
    subtitle: "A Brief History of Humankind",
    author: "Yuval Noah Harari",
    published: "2017-08-15",
    publisher: "HarperAudio",
    pages: 420,
    category: "Self-Help Books",
    price: 60.99,
    countInStock: 3,
    rating: 4.5,
    numReviews: 13,
    image: "/images/book4.png",
  },
  {
    _id: "5",
    title: "It Starts with Us",
    subtitle: "A Novel (2) (It Ends with Us)",
    author: "Colleen Hoover",
    published: "2022-10-18",
    publisher: "Atria Books",
    pages: 336,
    category: "Romance Books",
    price: 50,
    countInStock: 0,
    rating: 4.0,
    numReviews: 10,
    image: "/images/book5.png",
  },
];

export default books;
